### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sreichel** [netz98/N98_LayoutHelper#11]
Hi,

can you please add a new release?

Kind regards.

**Comment by cmuench** [comment]
@sreichel We do not plan to release a new version because we do not have any Magento 1 project where we need that.
Do you have any issues?

**Comment by sreichel** [comment]
@cmuench No issues, just want to get latest version when installing via composer. PR that raies version in config.xml?

**Comment by cmuench** [comment]
@sreichel https://packagist.org/packages/n98/n98_layouthelper

**Comment by sreichel** [comment]
Thanks.
