### ISSUE TITLE
Question: OpenMage integration?

### ISSUE THREAD

**Issue by sreichel** [netz98/N98_LayoutHelper#12]
Hi,

am i allowed to port changes from `Block/Page/Html/Head.php` to OpenMage? Breadcrumb features are ported from there and other code is already same ... this would make netz98/N98_LayoutHelper obsolete for OpenMage users?

Maybe add OSL3 license?

Regards

**Comment by cmuench** [comment]
@sreichel Yes, take whatever your want. We do not plan to update this module in the future.
