### ISSUE TITLE
Links are still showing up / further documentation needed?

### ISSUE THREAD

**Issue by Chris8080** [netz98/N98_LayoutHelper#8]
Hello,

I integrated the Extension but nothing happens - so some further questions:

Will I see it in the Magento Connect Manager?
Where do I have to put the XML code? Inside <config> or inside <admin> or ...?
Are these correct with 1.9.1.0:

```
                        <action method="removeLink"><name>OAuth Customer Tokens</name></action>
                        <action method="removeLink"><name>billing_agreements</name></action>
                        <action method="removeLink"><name>recurring_profiles</name></action>
                        <action method="removeLink"><name>downloadable</name></action>
```

Thank you in advance,
Chris

**Comment by ktomk** [comment]
"Nothing happens" is not a good description for an error report. What did you do? What did happen? What did you expect to happen?

Regarding your questions:

> Will I see it in the Magento Connect Manager?

I'm not very familiar with this extension and even less familiar with the Magento Connect Manage but I'd say: most likely *not*.

> Where do I have to put the XML code? Inside or inside or ...?

Which XML code are you referring to? And what does "Inside" or "inside" or "..." look like, which places do you describe here? I guess you're talking about local.xml but that file can grow to quite some extend. 

> Where do I have to put the XML code? Inside or inside or ...? [...]

That depends where you place those. It's not clear form your question what the (x)path of the parent document element is. Generally the XML you presented could represent a valid (correct) use.

**Comment by Chris8080** [comment]
Wow! Thanks a lot for your fast reply! :)

I downloaded the zip file and extracted it.
app/etc/modules/N98_LayoutHelpers.xml
app/code/community/N98/LayoutHelper
I logged out, deleted the cache, logged in again.

Then I used this local.xml:
```
<config>
    <global>
        <install>
            <date><![CDATA[Thu, 02 Apr 2015 03:23:49 +0000]]></date>
        </install>
        <crypt>
            <key><![CDATA[__]]></key>
        </crypt>
        <disable_local_modules>false</disable_local_modules>
        <resources>
            <db>
                <table_prefix><![CDATA[__]]></table_prefix>
            </db>
            <default_setup>
                <connection>
                    <host><![CDATA[localhost]]></host>
                    <username><![CDATA[__]]></username>
                    <password><![CDATA[__]]></password>
                    <dbname><![CDATA[__]]></dbname>
                    <initStatements><![CDATA[SET NAMES utf8]]></initStatements>
                    <model><![CDATA[mysql4]]></model>
                    <type><![CDATA[pdo_mysql]]></type>
                    <pdoType><![CDATA[]]></pdoType>
                    <active>1</active>
                </connection>
            </default_setup>
        </resources>
        <session_save><![CDATA[files]]></session_save>
    </global>
    <admin>
        <routers>
            <adminhtml>
                <args>
                    <frontName><![CDATA[__]]></frontName>
                </args>
            </adminhtml>
        </routers>
    </admin>

        <customer_account>
                <reference name="customer_account_navigation">
                        <action method="removeLink"><name>OAuth Customer Tokens</name></action>
                        <action method="removeLink"><name>billing_agreements</name></action>
                        <action method="removeLink"><name>recurring_profiles</name></action>
                        <action method="removeLink"><name>downloadable</name></action>
                </reference>
        </customer_account>
</config>
```
And I cleaned the cache again, logged in as a user, but I still see all the links (application, billing, recurring and downloadable) on the left side of my account:
index.php/customer/account/

**Comment by ktomk** [comment]
Okay now I see. Please use the `local.xml` file in the layout directory. You edited the config file. This module is related to layout. That should solve your issue.

**Comment by Chris8080** [comment]
Ah, I see - now I've put:
'''
<customer_account>
    <reference name="customer_account_navigation">
        <action method="removeLink"><name>OAuth Customer Tokens</name></action>
        <action method="removeLink"><name>billing_agreements</name></action>
        <action method="removeLink"><name>recurring_profiles</name></action>
    </reference>
</customer_account>
'''
into a file:
app/design/frontend/default/em0121/layout/local.xml
(none of my themes, not even the default theme, had a local.xml - so I hope I've put it into the right directory now?)
That's all there is in the local.xml file now (do you have a sample to compare it maybe?)

The changes don't influence my navigation, even after clearing the cache. 
Maybe there need to be another element in the XML tree?

**Comment by ktomk** [comment]
@Chris8080: The layout local.xml in Magento is especially used when you want to make your theme more portable. It's not a must. So here are some articles I think that should suit your needs in understanding the Magento layout local.xml better:

- [Use a Local.xml File (by  Tatiana Kozyreva; Jan 2014)](http://blog.belvg.com/use-a-local-xml-file.html)
- [The Better Way to Modify Magento Layouts (by Erik Hansen; Feb 2010)](http://www.classyllama.com/blog/the-better-way-to-modify-magento-layouts)
- [5 Useful Tricks For Your Magento local.xml (by Robert Popovic; Jun 2011)](http://magebase.com/magento-tutorials/5-useful-tricks-for-your-magento-local-xml/)

You need to follow the nomenclature which should become visible from the examples given in those references. Please let me know if this information is helpful for you.

**Comment by sreichel** [comment]
Can this one be closed? ;)

**Comment by cmuench** [comment]
@sreichel done
